print(" ___ ___ ___ ___ ___ ___ ___ ___ ")
print("|   |   |   |   |   |   |   |   |")
print("| R | N | B | Q | K | B | N | R |")
print("|___|___|___|___|___|___|___|___|")
print("|   |   |   |   |   |   |   |   |")
print("| P | P | P | P | P | P | P | P |")
print("|___|___|___|___|___|___|___|___|")
print("|   |   |   |   |   |   |   |   |")
print("|   |   |   |   |   |   |   |   |")
print("|___|___|___|___|___|___|___|___|")
print("|   |   |   |   |   |   |   |   |")
print("|   |   |   |   |   |   |   |   |")
print("|___|___|___|___|___|___|___|___|")
print("|   |   |   |   |   |   |   |   |")
print("|   |   |   |   |   |   |   |   |")
print("|___|___|___|___|___|___|___|___|")
print("|   |   |   |   |   |   |   |   |")
print("|   |   |   |   |   |   |   |   |")
print("|___|___|___|___|___|___|___|___|")
print("|   |   |   |   |   |   |   |   |")
print("| P | P | P | P | P | P | P | P |")
print("|___|___|___|___|___|___|___|___|")
print("|   |   |   |   |   |   |   |   |")
print("| R | N | B | K | Q | B | N | R |")
print("|___|___|___|___|___|___|___|___|")
#im gonna be setting up the github so we don't have to activate multiplayer mode each time and we can work on it when the other's not online
#just a sec
#ok
#almost done gotta verify my email..
